// demo-react/src/UploadFile.js
import React, { Component } from "react";
import { ImageCompressor, getImageSize } from "compressor-img";
import { FaUpload } from "react-icons/fa";

class UploadFile extends Component {
  constructor(props) {
    super(props);
    this.state = {
      originalImage: null,
      sizeOriganleImage: null,
      compressedImage: null,
      sizeCompressedImage: null
    };
  }

  handleImageChange = event => {
    event.preventDefault();
    const { documentKey } = this.props;

    if (event.target.files.length !== 0) {
      let reader = new FileReader();
      let file = event.target.files[0];

      reader.onloadend = () => {
        let imageCompressor = new ImageCompressor({
          onSuccess: response => {
            this.setState({
              originalImage: response.original,
              sizeOriganleImage: getImageSize(response.original),
              compressedImage: response.compressed,
              sizeCompressedImage: getImageSize(response.compressed)
            });
            console.log(response);
          },
          scale: 70,
          quality: 70,
          holdCompress: false,
          originalImage: reader.result
        });
        imageCompressor.startCompress();
      };

      reader.readAsDataURL(file);
    }
  };

  render() {
    return (
      <div className="upload-file-container">
        <div className="upload-file-input">
          <label htmlFor="file">
            <div className="upload-type">
              <FaUpload className="icon" />
              <span> Upload File </span>
            </div>
          </label>
          <input
            id="file"
            style={{ display: "none" }}
            type="file"
            onChange={this.handleImageChange}
          />
        </div>
        <div className="display-compressed-image">
          {this.state.sizeOriganleImage &&
            this.state.sizeOriganleImage +
              " kb  -> " +
              this.state.sizeCompressedImage +
              " kb"}
          {this.state.compressedImage && (
            <img
              style={{
                maxWidth: "600px",
                maxheight: "400px"
              }}
              src={this.state.compressedImage}
            />
          )}
        </div>
      </div>
    );
  }
}
export default UploadFile;

// demo-angular/src/app/upload-file/upload-file.component.ts
import { Component, OnInit } from "@angular/core";
import { ImageCompressor, getImageSize } from "compressor-img";
@Component({
  selector: "app-upload-file",
  templateUrl: "./upload-file.component.html",
  styleUrls: ["./upload-file.component.css"]
})
export class UploadFileComponent implements OnInit {
  originalImage: any = null;
  sizeOriganleImage: any = null;
  compressedImage: any = null;
  sizeCompressedImage: any = null;
  constructor() {}

  handleImageChange(event) {
    if (event.target.files.length !== 0) {
      let reader = new FileReader();
      let file = event.target.files[0];

      reader.onloadend = () => {
        let imageCompressor = new ImageCompressor({
          onSuccess: response => {
            (this.originalImage = response.original),
              (this.sizeOriganleImage = getImageSize(response.original)),
              (this.compressedImage = response.compressed),
              (this.sizeCompressedImage = getImageSize(response.compressed));
          },
          scale: 70,
          quality: 70,
          holdCompress: false,
          originalImage: reader.result
        });
        imageCompressor.startCompress();
      };

      reader.readAsDataURL(file);
    }
  }
  ngOnInit() {}
}

<div class="upload-file-container">
  <div class="upload-file-input">
    <label for="file">
      <div class="upload-type">

        <span> Upload File </span>
      </div>
    </label>
    <input id="file" type="file" (change)="handleImageChange($event)" />
  </div>
  <div class="display-compressed-image">
    <div *ngIf="sizeOriganleImage"> {{sizeOriganleImage}} kb -> {{sizeCompressedImage}} kb </div>
    <img *ngIf="compressedImage" class="image-compressed" src="{{compressedImage}}" />
  </div>
</div>
